DROP TABLE IF EXISTS alerts_copy_tmp;
CREATE TABLE alerts_copy_tmp AS select alerts.alertid,alerts.actionid,alerts.eventid,alerts.userid,alerts.clock,alerts.mediatypeid,alerts.sendto,alerts.subject,alerts.message,alerts.status,alerts.retries,alerts.error,alerts.esc_step,alerts.alerttype,alerts.p_eventid,alerts.acknowledgeid from alerts inner join events on  events.eventid=alerts.eventid;
DROP TABLE IF EXISTS alerts;
ALTER TABLE alerts_copy_tmp RENAME TO alerts;
DROP TABLE IF EXISTS acknowledges_copy_tmp;
CREATE TABLE acknowledges_copy_tmp AS select acknowledges.acknowledgeid,acknowledges.userid,acknowledges.eventid,acknowledges.clock,acknowledges.message,acknowledges.action,acknowledges.old_severity,acknowledges.new_severity from acknowledges inner join events on  events.eventid=acknowledges.eventid;
DROP TABLE IF EXISTS acknowledges;
ALTER TABLE acknowledges_copy_tmp RENAME TO acknowledges;
DROP TABLE IF EXISTS event_tag_copy_tmp;
CREATE TABLE event_tag_copy_tmp AS select event_tag.eventtagid,event_tag.eventid,event_tag.tag,event_tag.value from event_tag inner join events on  events.eventid=event_tag.eventid;
DROP TABLE IF EXISTS event_tag;
ALTER TABLE event_tag_copy_tmp RENAME TO event_tag;
DROP TABLE IF EXISTS problem_copy_tmp;
CREATE TABLE problem_copy_tmp AS select problem.eventid,problem.source,problem.object,problem.objectid,problem.clock,problem.ns,problem.r_eventid,problem.r_clock,problem.r_ns,problem.correlationid,problem.userid,problem.name,problem.acknowledged,problem.severity  from problem left join events on  events.eventid=problem.eventid;
DROP TABLE IF EXISTS problem;
ALTER TABLE problem_copy_tmp RENAME TO problem;
DROP TABLE IF EXISTS problem_tag_copy_tmp;
CREATE TABLE problem_tag_copy_tmp AS select problem_tag.problemtagid,problem_tag.eventid,problem_tag.tag,problem_tag.value from problem_tag inner join events on  events.eventid=problem_tag.eventid;
DROP TABLE IF EXISTS problem_tag;
ALTER TABLE problem_tag_copy_tmp RENAME TO problem_tag;
DROP TABLE IF EXISTS event_recovery_copy_tmp;
CREATE TABLE event_recovery_copy_tmp AS select event_recovery.eventid,event_recovery.r_eventid,event_recovery.c_eventid,event_recovery.correlationid,event_recovery.userid  from event_recovery inner join events on  events.eventid=event_recovery.eventid;
DROP TABLE IF EXISTS event_recovery;
ALTER TABLE event_recovery_copy_tmp RENAME TO event_recovery;
DROP TABLE IF EXISTS auditlog_details_copy_tmp;
CREATE TABLE auditlog_details_copy_tmp AS select auditlog_details.auditdetailid,auditlog_details.auditid,auditlog_details.table_name,auditlog_details.field_name,auditlog_details.oldvalue,auditlog_details.newvalue  from auditlog_details inner join auditlog on  auditlog_details.auditid=auditlog.auditid;
DROP TABLE IF EXISTS auditlog_details;
ALTER TABLE auditlog_details_copy_tmp RENAME TO auditlog_details;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO zabbix;
